# Generated by Django 2.2 on 2022-03-16 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_auto_20220316_1635'),
        ('shop', '0003_auto_20220316_1625'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categ',
            options={},
        ),
        migrations.DeleteModel(
            name='products',
        ),
    ]
